[config]
save_dir="dir_tmaze_er_10_deep_a"
exp_file="experiment/dir_tmaze_er.jl"
exp_module_name = "DirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8

warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000

deep = true

[sweep_args]
cell+numhidden+internal = [["AARNN", 18, 50], ["AARNN", 18, 20], ["AARNN", 30, 4], ["AAGRU", 10, 50], ["AAGRU", 10, 14], ["AAGRU", 17, 4]]
replay_size = [10000, 20000]
eta = "0.01*(2.0.^(-11:2:-3))"
truncation = [12, 20]
seed = "1:20"
