[config]
save_dir="ringworld_er_rmsprop_6"
exp_file="experiment/ringworld_er.jl"
exp_module_name = "RingWorldERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 200000
opt = "RMSProp"
rho = 0.9
size = 6
batch_size = 4
replay_size = 1000
warm_up = 1000
target_update_freq = 1000

outgamma = 0.9
action_features = false
synopsis = true


[sweep_args]
outhorde = ["onestep", "gammas_term"]
cell = ["MARNN", "AARNN", "RNN"]
hs_learnable = [false, true]
update_freq = [4, 16]
eta = [0.0001, 0.0005, 0.005, 0.001]
truncation = [1, 2, 3, 4, 5, 6, 8, 10, 12, 16]
numhidden = [3, 6, 9, 12]
seed = "1:10"