[config]
save_dir="ringworld_er_rmsprop_10_fac_tuc_lc"
exp_file="experiment/ringworld_er.jl"
exp_module_name = "RingWorldERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.9
size = 10
batch_size = 4
replay_size = 1000
warm_up = 1000
target_update_freq = 1000

outgamma = 0.9
action_features = false
synopsis = true

outhorde = "gammas_term"
hs_learnable = true
update_freq = 4
truncation = 6

[sweep_args]
"cell+numhidden+out_factors+in_factors+action_factors+factors" = [["AARNN", 15, 0, 0, 0, 0], ["MARNN", 12, 0, 0, 0, 0], ["FacMARNN", 15, 0, 0, 0, 12], ["FacMARNN", 12, 0, 0, 0, 14], ["FacTucMARNN", 15, 7, 7, 2, 0], ["FacTucMARNN", 12, 9, 9, 2, 0], ["AAGRU", 12, 0, 0, 0, 0], ["MAGRU", 9, 0, 0, 0, 0], ["FacMAGRU", 12, 0, 0, 0, 8], ["FacMAGRU", 9, 0, 0, 0, 12], ["FacTucMAGRU", 12, 7, 7, 2, 0], ["FacTucMAGRU", 9, 9, 9, 2, 0]] 
eta = "0.1 .* 1.6 .^(-16:3:-4)"
seed = "1:20"
