[config]
save_dir="image_dir_tmaze_adam_6"
exp_file="experiment/viz_dir_tmaze.jl"
exp_module_name = "VisualDirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"steps" = 400000

"opt" = "ADAM"
"size" = 6
"gamma" = 0.9

"batch_size" = 16
"replay_size" = 50000
"warm_up" = 1000
"hs_learnable" = true
"update_wait" = 4
"target_update_wait" = 10000

"latent_size" = 128
"output_size" = 128

"cell" = "FacMAGRU"

[sweep_args]
"eta" = "(2.0.^(-20:2:-4))"
"truncation" = [10, 12]
"numhidden_factors" = [[32, 259], [64, 350], [70, 164], [132, 208]]
"seed" = "1:5"