[config]
save_dir="ringworld_fac_er_rmsprop_10_magru"
exp_file="experiment/ringworld_er.jl"
exp_module_name = "RingWorldERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.9
size = 10
batch_size = 4
replay_size = 1000
warm_up = 1000
target_update_freq = 1000

outgamma = 0.9
action_features = false
synopsis = true

outhorde = "gammas_term"
hs_learnable = true
update_freq = 4

[sweep_args]
cell = ["FacMAGRU"]
eta = "0.1 .* 1.6 .^(-16:3:-2)"
truncation = [1, 2, 4, 6, 10, 15]
numhidden_factors = [[6, 10], [15, 23], [20, 31], [9, 14], [12, 19], [17, 26], [3, 5]]
seed = "1:20"