[config]
save_dir="dir_tmaze_er_deep_a_final"
exp_file="experiment/dir_tmaze_er.jl"
exp_module_name = "DirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8

warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000
replay_size = 10000

deep = true

truncation = 12
internal_o = 12
internal_a = 6

[sweep_args]
"cell+numhidden+eta" = [["AARNN", 30, 0.000372529], ["MARNN", 18, 0.00014552], ["AAGRU", 17, 0.000953674], ["MAGRU", 10, 0.000372529]]
seed = "21:120"
