[config]
save_dir="image_dir_tmaze_deep_a"
exp_file="experiment/viz_dir_tmaze.jl"
exp_module_name = "VisualDirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 400000

opt = "ADAM"
size = 6
gamma = 0.9

batch_size = 16
replay_size = 50000
warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 10000

latent_size = 128	
output_size = 128
internal_a = 64

deep = true

[sweep_args]
cell_numhidden = [["AAGRU", 132], ["MAGRU", 64]]
eta = "(2.0.^(-20:2:-6))"
truncation = [12, 20]
seed = "1:5"