[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_ringworld_er_deep_a_v2"
save_dir="ringworld_er_deep_a_v2"
exp_file="experiment/RingWorldERExperiment.jl"
exp_module_name = "RingWorldERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iterV2"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.9
size = 10
batch_size = 4
replay_size = 1000
warm_up = 1000
target_update_freq = 1000

outgamma = 0.9
action_features = false
synopsis = true

outhorde = "gammas_term"
hs_learnable = true
update_freq = 4

deepaction=true

[sweep_args]
"cell+numhidden+internal_a" = [["AARNN", 4, 4], ["AARNN", 12, 2], ["AAGRU", 9, 10]]
internal_a_layers = [1, 2, 4]
eta = "0.1 .* 1.6 .^(-16:3:-2)"
truncation = [1, 2, 4, 6, 8, 10, 12, 15]
seed = "1:10"