[config]
save_dir="ringworld_er_deep_a"
exp_file="experiment/ringworld_er.jl"
exp_module_name = "RingWorldERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.9
size = 10
batch_size = 4
replay_size = 1000
warm_up = 1000
target_update_freq = 1000

outgamma = 0.9
action_features = false
synopsis = true

outhorde = "gammas_term"
hs_learnable = true
update_freq = 4


[sweep_args]
deep = [true, false]
"cell+numhidden" = [["AARNN", 15], ["MARNN", 12], ["AAGRU", 12], ["MAGRU", 9]]
eta = "0.1 .* 1.6 .^(-16:3:-2)"
truncation = [10]
seed = "1:10"