[config]
save_dir="dir_tmaze_online_rmsprop_10_fac_tuc"
exp_file="experiment/dir_tmaze_online.jl"
exp_module_name = "DirectionalTMazeOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99
size = 10
gamma = 0.99

truncation = 16

[sweep_args]
"cell+numhidden+action_factors+in_factors+out_factors" = [["FacTucMARNN", 46, 3, 16, 16], ["FacTucMARNN", 36, 3, 18, 18], ["FacTucMARNN", 27, 3, 20, 20], ["FacTucMAGRU", 26, 3, 15, 15], ["FacTucMAGRU", 20, 3, 17, 17], ["FacTucMAGRU", 15, 3, 20, 20]]
eta = "0.1 .* 1.6 .^(-16:3:-4)"
seed = "1:20"
