[config]
save_dir="dir_tmaze_online_rmsprop_10_fac"
exp_file="experiment/dir_tmaze_online.jl"
exp_module_name = "DirectionalTMazeOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99
size = 10
gamma = 0.99

truncation = 16

[sweep_args]
"cell+numhidden+factors+init_style" = [["FacMARNN", 46, 24, "tensor"], ["FacMARNN", 46, 24, "standard"], ["FacMARNN", 46, 24, "ignore"], ["MARNN", 27, 0, "na"], ["FacMAGRU", 26, 21, "tensor"], ["FacMAGRU", 26, 21, "standard"], ["MAGRU", 15, 0, "na"]]
eta = "0.1 .* 1.6 .^(-16:3:-4)"
seed = "1:20"
