[config]
save_dir="dir_tmaze_online_rmsprop_10_fac_sweep"
exp_file="experiment/dir_tmaze_online.jl"
exp_module_name = "DirectionalTMazeOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99
size = 10
gamma = 0.99

truncation = 16
init_style = "tensor"

[sweep_args]
"cell+numhidden+factors" = [["FacMARNN", 27, 40], ["FacMARNN", 27, 75], ["FacMARNN", 27, 100], ["FacMARNN", 36, 31], ["FacMARNN", 36, 75], ["FacMARNN", 36, 100], ["FacMARNN", 46, 24], ["FacMARNN", 46, 75], ["FacMARNN", 46, 100], ["FacMAGRU", 15, 37], ["FacMAGRU", 15, 75], ["FacMAGRU", 15, 100], ["FacMAGRU", 20, 28], ["FacMAGRU", 20, 75], ["FacMAGRU", 20, 100], ["FacMAGRU", 26, 21], ["FacMAGRU", 26, 75], ["FacMAGRU", 26, 100]]
eta = "0.1 .* 1.6 .^(-16:3:-4)"
seed = "1:10"
