[config]
save_dir="dir_tmaze_online_rmsprop_6"
exp_file="experiment/dir_tmaze_online.jl"
exp_module_name = "DirectionalTMazeOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99
size = 6
gamma = 0.99

[sweep_args]
cell = ["MARNN", "AARNN", "RNN", "MAGRU", "AAGRU", "GRU"]
eta = "0.01*(2.0.^(-11:2:-2))"
truncation = [1, 2, 4, 6, 8, 12, 16]
numhidden = [3, 6, 9, 12]
seed = "1:10"