info = """
This experiment is to sweep over the gating network to teset how well the naive active gating
network performs in a control task. Part 2
"""

[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_dir_tmaze_gn_large" # Database name
save_dir="dir_tmaze_gn_large"
exp_file="experiment/DirectionalTMazeERExperiment.jl"
exp_module_name = "DirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iterV2"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8
warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000

gating_network = {name="default", layers=[[10, "relu"], [10, "relu"]]}

[sweep_args]
"cell+numhidden" = [["AGMoERNN", 30], ["AGMoERNN", 18]]
eta = "0.01*(2.0.^(-13:2:4))"
truncation = [12]
num_experts = [3, 6, 9, 12, 15]
replay_size = [10000, 20000]
gating_network.layers."1*2".1 = [8, 16, 32, 64, 128, 256, 512]
seed = "1:10"