info="""
This experiment is to test the gating network code and see if we can learn in ring world. This
experiment is primarily focused on the gating network.
"""

[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_ringworld_moe_gating_network" # Database name
save_dir="ringworld_moe_gating_network"
exp_file="experiment/RingWorldERExperiment.jl"
exp_module_name = "RingWorldERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iterV2"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.9
size = 10
batch_size = 4
replay_size = 1000
warm_up = 1000
target_update_freq = 1000

outgamma = 0.9
action_features = false
synopsis = true

outhorde = "onestep"
hs_learnable = true
update_freq = 4

gating_network = {name="default", layers=[[10, "relu"], [10, "relu"]]}

[sweep_args]
"cell+numhidden" = [["AGMoERNN", 12], ["AGMoEGRU", 9]]
eta = "0.1 .* 1.6 .^(-13:1:-7)"
truncation = [1, 2, 4, 6, 8, 10, 12, 15]
num_experts = [2, 4, 8, 12, 24]
gating_network.layers."1*2".1 = [8, 16, 32, 64, 128]
seed = "1:10"