info="""
This experiment is to test the gating network code and see if we can learn in ring world.
"""

[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_ringworld_active_gating_moe" # Database name
save_dir="ringworld_active_gating_moe"
exp_file="experiment/RingWorldERExperiment.jl"
exp_module_name = "RingWorldERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 5000
opt = "RMSProp"
rho = 0.9
size = 10
batch_size = 4
replay_size = 1000
warm_up = 1000
target_update_freq = 1000

outgamma = 0.9
action_features = false
synopsis = true

outhorde = "onestep"
hs_learnable = true
update_freq = 4

gating_network = {name="default", "layers"=[[10, "relu"], [10, "relu"]]}

[sweep_args]
"cell+numhidden" = [["AGMoERNN", 12], ["AGMoEGRU", 9]]
eta = "0.1 .* 1.6 .^(-16:3:-2)"
truncation = [1, 2, 4, 6, 8, 10, 12, 15]
num_experts = [1, 2, 4, 8]
seed = "1:10"