[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_tmaze_moe_gating_network" # Database name
save_dir="tmaze_er_moe_sweeps"
exp_file="experiment/TMazeERExperiment.jl"
exp_module_name = "TMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iterV2"


[static_args]
steps = 300000
size = 10

opt = "RMSProp"
rho = 0.99

gamma = 0.99

batch_size = 4
replay_size = 1000
warm_up = 1000
update_wait = 4
target_update_wait = 1000
hs_learnable = true

gating_network = {name="default", layers=[[10, "relu"], [10, "relu"]]}

[sweep_args]
cell = ["AGMoERNN"]
numhidden = [6, 10]
gating_network.layers."1*2".1 = [8, 16, 32, 64]
eta = "0.01*(2.0.^(-13:-2))"
truncation = [8, 10, 16]
seed = "1:20"