[config]
save_dir="tmaze_online_rmsprop_10"
exp_file="experiment/tmaze_online.jl"
exp_module_name = "TMazeOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99
size = 10
gamma = 0.99

[sweep_args]
cell = ["MAGRU", "AAGRU", "GRU", "MARNN", "AARNN", "RNN"]
eta = "0.1 .* 1.6 .^(-16:3:-2)"
truncation = [8, 10, 12, 15, 20]
numhidden = [6, 10, 15, 17, 20]
seed = "1:10"