[config]
save_dir="dir_tmaze_er_combo_add"
exp_file="experiment/dir_tmaze_er.jl"
exp_module_name = "DirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8

warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000
replay_size = 20000

deep = false 

[sweep_args]
"cell+numhidden" = [["CaddRNN", 15], ["CaddRNN", 20], ["CaddRNN", 10]]
eta = "0.01*(1.6.^(-11:2:-1))"
truncation = [12, 20]
seed = "1:20"
