[config]
save_dir="dir_tmaze_er_rmsprop_10_gaialstm"
exp_file="experiment/dir_tmaze_er.jl"
exp_module_name = "DirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8
replay_size = 10000
warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000

truncation = 12
cell = "GAIALSTM"

[sweep_args]
eta = "0.1 .* 1.6 .^(-16:3:-4)"
"numhidden+internal" = [[5, 10], [4, 12], [7, 7], [10, 6], [10, 30]]
seed = "1:10"
