[config]
save_dir="dir_tmaze_gated_online_rmsprop_10"
exp_file="experiment/dir_tmaze_online.jl"
exp_module_name = "DirectionalTMazeOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99
size = 10
gamma = 0.99

truncation = 16
cell = "ActionGatedRNN"

[sweep_args]
"numhidden+internal" = [[15, 43], [20, 34], [26, 28]]
eta = "0.1 .* 1.6 .^(-16:3:-4)"
seed = "1:20"
