[config]
save_dir="dir_tmaze_gated_er_rmsprop_10_1M"
exp_file="experiment/dir_tmaze_er.jl"
exp_module_name = "DirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 100000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8
replay_size = 10000
warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000

truncation = 12

[sweep_args]
eta = "0.1 .* 1.6 .^(-16:3:-4)"
"cell+numhidden+factors+internal" = [["RNN", 30, 0, 0], ["AARNN", 30, 0, 0], ["MARNN", 18, 0, 0], ["FacMARNN", 25, 15, 0], ["GRU", 17, 0, 0], ["AAGRU", 17, 0, 0], ["MAGRU", 10, 0, 0], ["FacMAGRU", 15, 17, 0], ["ActionGatedRNN", 10, 0, 28], ["ActionGatedRNN", 15, 0, 21], ["ActionGatedRNN", 20, 0, 17]]
seed = "1:20"
