[config]
save_dir="final_ringworld_online_rmsprop_10_fac_tensor"
exp_file="experiment/ringworld_online.jl"
exp_module_name = "RingWorldOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.9
size = 10

outgamma = 0.9
action_features = false
synopsis = true

outhorde = "gammas_term"
hs_learnable = true
truncation = 12
eta = 0.0009094947

[sweep_args]
"cell+numhidden+factors+init_style" = [["FacMARNN", 20, 10, "tensor"], ["FacMAGRU", 12, 10, "tensor"]]
#eta = "0.1 .* 1.6 .^(-16:3:-4)"
seed = "21:120"
