[config]
save_dir="ringworld_online_rmsprop_10_fac"
exp_file="experiment/ringworld_online.jl"
exp_module_name = "RingWorldOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.9
size = 10

outgamma = 0.9
action_features = false
synopsis = true

outhorde = "gammas_term"
hs_learnable = true

[sweep_args]
"cell+numhidden+factors+init_style" = [["FacMARNN", 12, 14, "tensor"], ["FacMARNN", 15, 12, "tensor"], ["FacMARNN", 12, 14, "standard"], ["FacMARNN", 15, 12, "standard"], ["FacMARNN", 12, 14, "ignore"], ["FacMARNN", 15, 12, "ignore"], ["MARNN", 12, 0, "na"], ["AARNN", 15, 0, "na"], ["FacMAGRU", 9, 12, "tensor"], ["FacMAGRU", 12, 8, "tensor"], ["FacMAGRU", 9, 12, "standard"], ["FacMAGRU", 12, 8, "standard"], ["MAGRU", 9, 0, "na"], ["AAGRU", 12, 0, "na"]]
eta = "0.1 .* 1.6 .^(-16:3:-4)"
truncation = [1, 2, 4, 6, 10, 15]
seed = "1:10"
