[config]
save_dir="ringworld_online_rmsprop_10"
exp_file="experiment/ringworld_online.jl"
exp_module_name = "RingWorldOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.9
size = 10

hs_learnable = false
outgamma = 0.9
action_features = false
synopsis = true
outhorde = "gammas_term"

[sweep_args]
cell = ["MAGRU", "AAGRU", "GRU", "MARNN", "AARNN", "RNN"]
eta = "0.1 .* 1.6 .^(-16:3:-2)"
truncation = [1, 2, 4, 6, 10, 15]
numhidden = [3, 6, 9, 12, 15, 20]
seed = "1:10"
