[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_tmaze_er_combo_sm"
save_dir="tmaze_er_combo_sm"
exp_file="experiment/TMazeERExperiment.jl"
exp_module_name = "TMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iterV2"

[static_args]

steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99

batch_size = 4
replay_size = 1000
warm_up = 1000
update_wait = 4
target_update_wait = 1000

hs_learnable = true
deepaction = true

[sweep_args]
"cell+numhidden" = [["CsoftmaxElGRU", 6], ["CsoftmaxElRNN", 20]]
eta = "0.01*(2.0.^(-11:2:6))"
truncation = [10]
seed = "1:20"