[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_final_dir_tmaze_er_10_combo_sm" # Database name
save_dir="final_dir_tmaze_er_10_combo_sm"
exp_file="experiment/DirectionalTMazeERExperiment.jl"
exp_module_name = "DirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "looper"
run_param = "seed"
run_list = "21:120"
arg_file = "final_runs/dir_tmaze_10_combo_sm.jld2"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8

warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000

truncation = 12

save_extras = [["AgentModel", "rnn_sm_w_a", 100], ["AgentModel", "rnn_sm_w_m", 100]]