[config]
save_dir="final_dir_tmaze_6_er_rnn_rmsprop"
exp_file="experiment/dir_tmaze_er.jl"
exp_module_name = "DirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "looper"
run_param = "seed"
run_list = "20:50"
arg_file = "final_runs/dir_tmaze_6.jld2"


[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99
size = 6
gamma = 0.99
batch_size = 8
replay_size = 10000
warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000

