[config]
save_dir="final_lunar_lander_er_magru_with_action"
exp_file="experiment/LunarLanderExperiment.jl"
exp_module_name = "LunarLanderExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 4000000
opt = "RMSProp"
gamma = 0.99
batch_size = 32
warm_up = 1000
hs_learnable = true
target_update_wait = 1000
update_wait = 8
rho = 0.99
numhidden = 64
encoding_size = 128
omit_states = [6]
state_conditions = [2]
cell = "MAGRU"
replay_size = 100000

truncation = 16 
#eta = 0.00013877787807814446
eta = 0.0003552713678800499

save_extras = [["Agent", "action"]]

[sweep_args]
# eta = "0.1 .* 1.6 .^(-14:2:-12)"
seed = "11:30"