[config]
save_dir="final_lunar_lander_er_relu_rmsprop_os6_sc2_aagru_4M"
exp_file="experiment/lunar_lander.jl"
exp_module_name = "LunarLanderExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 4000000
opt = "RMSProp"
#opt = "ADAM"
gamma = 0.99
batch_size = 32
warm_up = 1000
hs_learnable = true
target_update_wait = 1000
update_wait = 8
rho = 0.99
#beta_m = 0.9
#beta_v = 0.99
numhidden = 152
replay_size = 100000

encoding_size = 128
omit_states = [6]
state_conditions = [2]

cell = "AAGRU"
truncation = 16
eta = 0.00013877787807814446

[sweep_args]
#eta = "0.1 .* 1.6 .^(-20:2:-6)"
#eta = "2.0 .^(-15:-10)"
#eta = "0.1 .* 1.6 .^(-16:2:-12)"
seed = "11:30"
