[config]
save_dir="final_lunar_lander_deep_a"
exp_file="experiment/LunarLanderExperiment.jl"
exp_module_name = "LunarLanderExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iterV2"

[static_args]
steps = 4000000
opt = "RMSProp"
gamma = 0.99
batch_size = 32
warm_up = 1000
hs_learnable = true
target_update_wait = 1000
update_wait = 8
rho = 0.99
replay_size = 100000

encoding_size = 128
omit_states = [6]
state_conditions = [2]

deep = true
internal_a = 64
truncation = 16

[sweep_args]
"cell+numhidden+eta" = [["AAGRU", 152, 0.00013877787807814446], ["MAGRU", 64, 0.00013877787807814446]]
seed = "11:30"
