[config]
save_dir="final_lunar_lander_er_relu_rmsprop_os6_sc2_facmagru64_4M"
exp_file="experiment/lunar_lander.jl"
exp_module_name = "LunarLanderExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 4000000
opt = "RMSProp"
gamma = 0.99
batch_size = 32
warm_up = 1000
hs_learnable = true
target_update_wait = 1000
update_wait = 8
rho = 0.99
numhidden = 64
factors = 380
encoding_size = 128
omit_states = [6]
state_conditions = [2]
cell = "FacMAGRU"
replay_size = 100000

truncation = 16 
eta = 0.0003552713678800499 

[sweep_args]
#eta = "0.1 .* 1.6 .^(-20:2:-6)"
seed = "11:30"
