[config]
save_dir="final_tmaze_er_rnn_rmsprop_10"
exp_file="experiment/tmaze_er.jl"
exp_module_name = "TMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "looper"
run_param = "seed"
run_list = "20:50"
arg_file = "final_runs/tmaze_10.jld2"

[static_args]
"steps" = 300000
"opt" = "RMSProp"
"rho" = 0.99
"size" = 10
"gamma" = 0.99
"batch_size" = 4
"replay_size" = 1000
"warm_up" = 1000