[config]
save_dir="final_image_dir_tmaze_adam_6"
exp_file="experiment/viz_dir_tmaze.jl"
exp_module_name = "VisualDirectionalTMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "looper"
run_param = "seed"
run_list = "21:40"
arg_file = "final_runs/viz_dir_tmaze.jld2"

[static_args]
"steps" = 400000

"opt" = "ADAM"
"size" = 6
"gamma" = 0.9

"batch_size" = 16
"replay_size" = 50000
"warm_up" = 1000
"hs_learnable" = true
"update_wait" = 4
"target_update_wait" = 10000

"latent_size" = 128
"output_size" = 128