[config]
save_dir="ringworld_online_rmsprop_size10"
exp_file="experiment/ringworld.jl"
exp_module_name = "RingWorldOnlineExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"steps" = 300000
"opt" = "RMSProp"
"rho" = 0.9
"size" = 10

"hs_learnable" = false
"outgamma" = 0.9
"action_features" = false
"synopsis" = true

[sweep_args]
"outhorde" = ["one_step", "gammas_term"]
"cell" = ["MAGRU", "AAGRU", "GRU", "MARNN", "AARNN", "RNN"]
"eta" = [0.0001, 0.0005, 0.005, 0.001]
"truncation" = [1, 2, 4, 6, 10, 16, 20, 25, 30]
"numhidden" = [3, 6, 9, 12, 15, 18, 20, 25, 30, 40]
"seed" = "1:10"

