[config]
save_dir="ringworld_er_rnn_rmsprop_20"
exp_file="experiment/ringworld_er.jl"
exp_module_name = "RingWorldExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"steps" = 500000
"opt" = "RMSProp"
"size" = 20
"batch_size" = 4
"replay_size" = 1000
"warm_up" = 1000
"target_update_freq" = 1000

"outgamma" = 0.9
"action_features" = false
"synopsis" = true

[sweep_args]
"outhorde" = ["onestep", "gammas_term"]
"cell" = ["MAGRU", "AAGRU", "GRU"]
"hs_learnable" = [true]
"update_freq" = [1, 4, 16]
"rho" = [0.9, 0.99]
"eta" = [0.0001, 0.0005, 0.005, 0.001]
"truncation" = [1, 4, 8, 16, 20, 30]
"numhidden" = [5, 10, 20] #[3, 6, 9, 12, 15, 20]
"seed" = "1:5"