[config]
save_dir="tmaze_er_rnn_rmsprop_10"
exp_file="experiment/tmaze_er.jl"
exp_module_name = "TMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iterV2"

[exp]
steps = 300000
seed = 1

[env]
name = "TMaze"
size = 10

[agent]
name = "Josh"
type = "DRQNAgent"
gamma = 0.99
batch_size = 4
replay_size = 1000
warm_up = 1000
target_update_wait = 1000
hs_learnable = true
update_wait = 4

[agent.optimizer]
name = "RMSProp"
eta = 0.0
rho = 0.99

[agent.network]
layer1 = {type="Dense", out=10, activation="relu"}
layer2 = {type="RNN", cell="AARNN", numhidden=10}
layer3 = {type="Dense", out="actions", activation="identity"}



[sweep_args]
agent.network.layer2."cell+numhidden" = [["MARNN", 9], ["AARNN", 15], ["RNN", 18]]
agent.optimizer.eta = "0.01*(2.0.^(-11:2:-2))"
agent.truncation = [8, 10, 11, 12, 16]
exp.seed = "1:10"