[config]
save_dir="tmaze_er_rnn_rmsprop_10"
exp_file="experiment/tmaze_er.jl"
exp_module_name = "TMazeERExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"steps" = 300000
"opt" = "RMSProp"
"rho" = 0.99
"size" = 10
"gamma" = 0.99
"batch_size" = 4
"replay_size" = 1000
"warm_up" = 1000
"target_update_wait" = 1000
"hs_learnable" = true
"update_wait" = 4

[sweep_args]
"cell" = ["MARNN", "AARNN", "RNN", "MAGRU", "AAGRU", "GRU"]
"eta" = "0.01*(2.0.^(-11:2:-2))"
"truncation" = [8, 10, 11, 12, 16]
"numhidden" = [6, 10, 15, 20]
"seed" = "1:10"