[config]
save_dir="lunar_lander_er_rmsprop"
exp_file="experiment/lunar_lander.jl"
exp_module_name = "LunarLanderExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 3000000
opt = "RMSProp"
gamma = 0.99
batch_size = 32
warm_up = 1000
hs_learnable = true
target_update_wait = 1000
update_wait = 8
rho = 0.99
numhidden = 128
encoding_size = 128
omit_states = [2, 3, 5]
state_conditions = []

[sweep_args]
replay_size = [10000, 100000]
cell = ["GRU", "AAGRU", "MAGRU"]
eta = "0.1 .* 1.6 .^(-18:2:-8)"
truncation = [4, 16, 32]
seed = "1:5"
