[config]
save_dir="lunar_lander_er_relu_rmsprop_os6_sc2_facmagru152_4M_wr"
exp_file="experiment/lunar_lander.jl"
exp_module_name = "LunarLanderExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 4000000
opt = "RMSProp"
gamma = 0.99
batch_size = 32
warm_up = 1000
hs_learnable = true
target_update_wait = 1000
update_wait = 8
rho = 0.99
numhidden = 152
factors = 170
encoding_size = 128
omit_states = [6]
state_conditions = [2]
cell = "FacMAGRU"
replay_size = 100000

truncation = 16 
#eta = 0.00013877787807814446

[sweep_args]
init_style = ["standard", "tensor"]
eta = "0.1 .* 1.6 .^(-14:2:-8)"
seed = "1:10"
