[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_inter_learn_straight_1_dir_tmaze_steps_v2" # Database name
save_dir="inter_learn_straight_1_dir_tmaze"
exp_file="experiment/DirectionalTMazeLearnInterExperiment.jl"
exp_module_name = "DirectionalTMazeLearnInterExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "looper"
run_param = "seed"
run_list = "21:70"
arg_file = "final_runs/dir_tmaze_10.jld2"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8
replay_size = 10000

warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000

deepaction = false

inter_list = "DTMazeStraight1_v2"
inter_num_steps = 20000
