[config]
save_backend="mysql" # mysql only database backend supported
database="mkschleg_inter_dir_tmaze_er_10" # Database name
save_dir="inter_dir_tmaze_er_10"
exp_file="experiment/DirectionalTMazeInterventionExperiment.jl"
exp_module_name = "DirectionalTMazeInterventionExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "looper"
run_param = "seed"
run_list = "21:120"
arg_file = "final_runs/dir_tmaze_10.jld2"

[static_args]
steps = 300000
opt = "RMSProp"
rho = 0.99

size = 10
gamma = 0.99
batch_size = 8
replay_size = 10000

warm_up = 1000
hs_learnable = true
update_wait = 4
target_update_wait = 1000

deepaction = false

inter_list = "DTMazeV1"
inter_freeze_training = true
inter_num_episodes = 5000



